controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile2.destroy(effects.fire, 500)
    music.zapped.play()
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        mySprite.vy = -170
    }
    music.baDing.play()
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    controller.moveSprite(mySprite)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    controller.moveSprite(mySprite)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.over(false, effects.clouds)
})
let projectile: Sprite = null
let projectile2: Sprite = null
let mySprite: Sprite = null
tiles.setTilemap(tilemap`level5`)
mySprite = sprites.create(assets.image`Ninja ghost`, SpriteKind.Player)
tiles.placeOnTile(mySprite, tiles.getTileLocation(1, 5))
mySprite.ay = 500
characterAnimations.loopFrames(
mySprite,
assets.animation`Ninja Ghost`,
200,
characterAnimations.rule(Predicate.Moving, Predicate.NotMoving)
)
game.onUpdateInterval(randint(5000, 10000), function () {
    projectile2 = sprites.createProjectileFromSide(img`
        ..............................
        ..............................
        ..............................
        ..............................
        ...........fffffffff..........
        .........ff444444444ff........
        ........f444fffffff444f.......
        .......f44ff5555555ff44f......
        ......f44f555fffff555f44f.....
        ......f4f55ff44444ff55f4f.....
        .....f44f5f444fff444f5f44f....
        .....f4f55f4ff555ff4f55f4f....
        .....f4f5f44f55f55f44f5f4f....
        .....f4f5f4f55fff55f4f5f4f....
        .....f4f5f4f5ff4ff5f4f5f4f....
        .....f4f5f4f55fff55f4f5f4f....
        .....f4f5f44f55f55f44f5f4f....
        .....f4f55f4ff555ff4f55f4f....
        .....f44f5f444fff444f5f44f....
        ......f4f55ff44444ff55f4f.....
        ......f44f555fffff555f44f.....
        .......f44ff5555555ff44f......
        ........f444fffffff444f.......
        .........ff444444444ff........
        ...........fffffffff..........
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        `, randint(-100, -80), 0)
    projectile2.follow(mySprite, 50)
    tiles.placeOnTile(projectile2, tiles.getTileLocation(8, 0))
    info.changeScoreBy(1)
})
game.onUpdateInterval(2000, function () {
    music.setTempo(40)
    projectile = sprites.createProjectileFromSide(assets.image`Ghost killers`, randint(-100, -80), 0)
    tiles.placeOnTile(projectile, tiles.getTileLocation(9, 5))
    info.changeScoreBy(1)
})
forever(function () {
    music.playMelody("D E G E F D E C ", 120)
})
